### PR TITLE
Ensuring support  for both emojis and the symbol "Đ" for Đogecoin😉

### PR DESCRIPTION
**Pull request by GreatApe42069**
Now, the isValidSymbol function checks for both emojis and the symbol "Đ" for Doge. The script will now validate whether the provided symbol is a valid emoji or the specified symbol. The provided modification includes the enhanced validation for symbols, ensuring support for both emojis and the symbol "Đ." Replaced the existing isSingleEmoji function with the updated isValidSymbol and I added the isSingleEmoji function for further emoji validation. Haven't got a chance to try it out yet though.

### CODE REVIEW

**Comment by fhhg9658** [comment]
if limit is 13J.
when I mint ，which one is correct?
(1) node dunes.js mintDune 5095510/16 13 J DU625sgfs56562556ddddddeeee
(2) node dunes.js mintDune 5095510/16 13J DU625sgfs56562556ddddddeeee
(3) node dunes.js mintDune 5095510/16 13 DU625sgfs56562556ddddddeeee

**Comment by sirduney** [comment]
Thanks for the PR. Can you please use the same code formatting as on master so that the diff only contains your changes?

**Comment by GreatApe42069** [comment]
I just resynced your original Repo to my forked repo, so all changes
including all new commits from your end and also all my changes and
differences should be showing properly now. If not let me know what you
need me to do to and I'll fix it.

**Comment by sirduney** [comment]
Having a look today ☝️

**Comment by sirduney** [comment]
There's still a noticeable difference in formatting. If you can adjust it so that the code isn't reformatted, I'll be able to merge it. Alternatively, I can handle the changes manually if you prefer. Check out [this line](https://github.com/sirduney/dunes-cli/pull/1/files#diff-14700dbd900932e53edad97e61ec2f1757de308567c8c17f52498337eb216b16L850) for reference.

**Comment by GreatApe42069** [comment]
Yea if you could handle it that would be great, I can just resync my fork
after you update so everyone has latest version.

**Pull request closed without merging**
